/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class QuartaTela extends javax.swing.JFrame {

    public DadosPessoais dadoAtual;

    public QuartaTela() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblTituloJanela = new javax.swing.JLabel();
        lblTMB1 = new javax.swing.JLabel();
        lblTMB2 = new javax.swing.JLabel();
        lblCalDia1 = new javax.swing.JLabel();
        lblCalDia2 = new javax.swing.JLabel();
        lblCalDiaObj1 = new javax.swing.JLabel();
        lblCalDiaObj2 = new javax.swing.JLabel();
        lblCalDiaObj3 = new javax.swing.JLabel();
        lblAgua1 = new javax.swing.JLabel();
        lblAgua2 = new javax.swing.JLabel();
        buttonAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contador de Calorias");
        setResizable(false);

        lblTituloJanela.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTituloJanela.setText("Calculadora de Calorias");

        lblTMB1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTMB1.setText("Taxa de metabolismo basal:");

        lblTMB2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        lblCalDia1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblCalDia1.setText("Calorias diarias:");

        lblCalDia2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        lblCalDiaObj1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblCalDiaObj1.setText("Calorias diarias para");

        lblCalDiaObj2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        lblCalDiaObj3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        lblAgua1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblAgua1.setText("Quantidade de água mínima diária:");

        lblAgua2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        buttonAvancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAvancar.setText("Sair");
        buttonAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblTituloJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTMB1)
                    .addComponent(lblCalDia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTMB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCalDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCalDiaObj1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCalDiaObj2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCalDiaObj3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgua1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgua2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloJanela)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTMB1)
                    .addComponent(lblTMB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalDia1)
                    .addComponent(lblCalDia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalDiaObj1)
                    .addComponent(lblCalDiaObj3)
                    .addComponent(lblCalDiaObj2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgua1)
                    .addComponent(lblAgua2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(buttonAvancar)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void buttonAvancarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    public void abrirQuartaJanela() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuartaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuartaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuartaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuartaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuartaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAvancar;
    private javax.swing.JLabel lblAgua1;
    public javax.swing.JLabel lblAgua2;
    private javax.swing.JLabel lblCalDia1;
    public javax.swing.JLabel lblCalDia2;
    private javax.swing.JLabel lblCalDiaObj1;
    public javax.swing.JLabel lblCalDiaObj2;
    public javax.swing.JLabel lblCalDiaObj3;
    private javax.swing.JLabel lblTMB1;
    public javax.swing.JLabel lblTMB2;
    private javax.swing.JLabel lblTituloJanela;
    // End of variables declaration
}
