/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TerceiraTela extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TerceiraTela() {
        initComponents();
    }

    public DadosPessoais dadoAtual;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroupFreqAtiv = new javax.swing.ButtonGroup();
        buttonGroupObjetivo = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo1 = new javax.swing.JLabel();
        jrbFreqAtiv1 = new javax.swing.JRadioButton();
        jrbFreqAtiv2 = new javax.swing.JRadioButton();
        jrbFreqAtiv3 = new javax.swing.JRadioButton();
        jrbFreqAtiv4 = new javax.swing.JRadioButton();
        jrbFreqAtiv5 = new javax.swing.JRadioButton();
        lblFreqAtiv1 = new javax.swing.JLabel();
        lblFreqAtiv2 = new javax.swing.JLabel();
        lblFreqAtiv3 = new javax.swing.JLabel();
        lblFreqAtiv4 = new javax.swing.JLabel();
        lblFreqAtiv5 = new javax.swing.JLabel();
        lblSubtitulo2 = new javax.swing.JLabel();
        jrbObjetivo1 = new javax.swing.JRadioButton();
        jrbObjetivo2 = new javax.swing.JRadioButton();
        jrbObjetivo3 = new javax.swing.JRadioButton();
        lblObjetivo1 = new javax.swing.JLabel();
        lblObjetivo2 = new javax.swing.JLabel();
        lblObjetivo3 = new javax.swing.JLabel();
        buttonAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Calorias");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo.setText("Calculadora de Calorias");

        lblSubtitulo1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblSubtitulo1.setText("Exercício físico semanal");

        buttonGroupFreqAtiv.add(jrbFreqAtiv1);
        jrbFreqAtiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFreqAtiv1ActionPerformed(evt);
            }
        });

        buttonGroupFreqAtiv.add(jrbFreqAtiv2);
        jrbFreqAtiv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFreqAtiv2ActionPerformed(evt);
            }
        });

        buttonGroupFreqAtiv.add(jrbFreqAtiv3);
        jrbFreqAtiv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFreqAtiv3ActionPerformed(evt);
            }
        });

        buttonGroupFreqAtiv.add(jrbFreqAtiv4);
        jrbFreqAtiv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFreqAtiv4ActionPerformed(evt);
            }
        });

        buttonGroupFreqAtiv.add(jrbFreqAtiv5);
        jrbFreqAtiv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFreqAtiv5ActionPerformed(evt);
            }
        });

        lblFreqAtiv1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFreqAtiv1.setText("Sedentário (pouco ou nenhum exercício)");

        lblFreqAtiv2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFreqAtiv2.setText("Levemente ativo (exercício leve - 1 a 3 dias)");

        lblFreqAtiv3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFreqAtiv3.setText("Moderadamente ativo (exercício moderado - 3 a 5 dias)");

        lblFreqAtiv4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFreqAtiv4.setText("Altamente ativo (exercício pesado - de 5 a 6 dias)");

        lblFreqAtiv5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFreqAtiv5.setText("Extremamente ativo (exercício pesado - diariamente e até 2 vezes por dia)");

        lblSubtitulo2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblSubtitulo2.setText("Objetivo");

        buttonGroupObjetivo.add(jrbObjetivo1);
        jrbObjetivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbObjetivo1ActionPerformed(evt);
            }
        });

        buttonGroupObjetivo.add(jrbObjetivo2);
        jrbObjetivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbObjetivo2ActionPerformed(evt);
            }
        });

        buttonGroupObjetivo.add(jrbObjetivo3);
        jrbObjetivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbObjetivo3ActionPerformed(evt);
            }
        });

        lblObjetivo1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblObjetivo1.setText("Ganhar massa");

        lblObjetivo2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblObjetivo2.setText("Perder peso");

        lblObjetivo3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblObjetivo3.setText("Manter peso");

        buttonAvancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAvancar.setText("Avançar");
        buttonAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbObjetivo1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblObjetivo2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbObjetivo2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblObjetivo3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbObjetivo3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblObjetivo1))
                                                        .addComponent(lblSubtitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblSubtitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbFreqAtiv1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFreqAtiv1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbFreqAtiv2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFreqAtiv2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbFreqAtiv3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFreqAtiv3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbFreqAtiv4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFreqAtiv4))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jrbFreqAtiv5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFreqAtiv5))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(163, 163, 163)
                                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addComponent(buttonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubtitulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbFreqAtiv1)
                                        .addComponent(lblFreqAtiv1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbFreqAtiv2)
                                        .addComponent(lblFreqAtiv2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbFreqAtiv3)
                                        .addComponent(lblFreqAtiv3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbFreqAtiv4)
                                        .addComponent(lblFreqAtiv4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbFreqAtiv5)
                                        .addComponent(lblFreqAtiv5))
                                .addGap(18, 18, 18)
                                .addComponent(lblSubtitulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbObjetivo1)
                                        .addComponent(lblObjetivo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbObjetivo2)
                                        .addComponent(lblObjetivo3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrbObjetivo3)
                                        .addComponent(lblObjetivo1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(buttonAvancar)
                                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jrbFreqAtiv1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbFreqAtiv2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbFreqAtiv3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbFreqAtiv4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbFreqAtiv5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbObjetivo1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbObjetivo2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jrbObjetivo3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonAvancarActionPerformed(java.awt.event.ActionEvent evt) {
        int TMB, caloriasDiarias, qtdAguaDiaria, objetivoCalorias;
        String objetivo = "";

        jrbFreqAtiv1.setActionCommand("1");
        jrbFreqAtiv2.setActionCommand("2");
        jrbFreqAtiv3.setActionCommand("3");
        jrbFreqAtiv4.setActionCommand("4");
        jrbFreqAtiv5.setActionCommand("5");
        jrbObjetivo1.setActionCommand("1");
        jrbObjetivo2.setActionCommand("2");
        jrbObjetivo3.setActionCommand("3");

        dadoAtual.setObjetivo(Integer.parseInt(buttonGroupObjetivo.getSelection().getActionCommand()));
        dadoAtual.setFreqAtividade(Integer.parseInt(buttonGroupFreqAtiv.getSelection().getActionCommand()));

        QuartaTela quartaTela = new QuartaTela();
        quartaTela.dadoAtual = dadoAtual;

        TMB = Calculos.TMB(dadoAtual);
        caloriasDiarias = Calculos.caloriasDiarias(dadoAtual, TMB);
        objetivoCalorias = Calculos.objetivoCalorias(caloriasDiarias, dadoAtual.getObjetivo());
        qtdAguaDiaria = Calculos.qtdAguaDiaria(dadoAtual);

        quartaTela.lblTMB2.setText(TMB + " calorias");
        quartaTela.lblCalDia2.setText(caloriasDiarias + " calorias");
        quartaTela.lblCalDiaObj3.setText(objetivoCalorias + " calorias");
        quartaTela.lblAgua2.setText(qtdAguaDiaria + " ml");

        switch (dadoAtual.getObjetivo())
        {
            case 1 -> objetivo = "perder peso:";
            case 2 -> objetivo = "manter peso:";
            case 3 -> objetivo = "ganhar massa:";
        }

        quartaTela.lblCalDiaObj2.setText(objetivo);

        quartaTela.setVisible(true);
        this.setVisible(false);
    }

    public void abrirTerceiraJanela() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerceiraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAvancar;
    private javax.swing.ButtonGroup buttonGroupFreqAtiv;
    private javax.swing.ButtonGroup buttonGroupObjetivo;
    private javax.swing.JRadioButton jrbFreqAtiv1;
    private javax.swing.JRadioButton jrbFreqAtiv2;
    private javax.swing.JRadioButton jrbFreqAtiv3;
    private javax.swing.JRadioButton jrbFreqAtiv4;
    private javax.swing.JRadioButton jrbFreqAtiv5;
    private javax.swing.JRadioButton jrbObjetivo1;
    private javax.swing.JRadioButton jrbObjetivo2;
    private javax.swing.JRadioButton jrbObjetivo3;
    private javax.swing.JLabel lblFreqAtiv1;
    private javax.swing.JLabel lblFreqAtiv2;
    private javax.swing.JLabel lblFreqAtiv3;
    private javax.swing.JLabel lblFreqAtiv4;
    private javax.swing.JLabel lblFreqAtiv5;
    private javax.swing.JLabel lblObjetivo1;
    private javax.swing.JLabel lblObjetivo2;
    private javax.swing.JLabel lblObjetivo3;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblSubtitulo2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration
}
